.TH CCASH_CMD 1 ccash_cmd\-VERSION
.SH NAME
ccash_cmd \- command line interface for ccash servers
.SH SYNOPSIS
.SY ccash_cmd
.OP "-n|--name" name
.OP "-p|--passwd" password
.OP "-c|--amount" amount
.OP "-t|--time" time
.OP "-a|--auth" auth
.OP "-s|--server" server
.YS
.SH DESCRIPTION
\fBccash_cmd\fP(1) is a command line utility for interfacing with \fBCCash\fP
servers.  It focuses on efficiency and is thus written with configuration in
mind.  Furthermore, simple flags and output formatting increase command
throughput.
.SH OPTIONS
.TP
Name
Sends a name with the request.  The provided name must conform with
.B CCash
username restrictions: be between 3 and 16 characters long and be composed of
lowercase letters, numbers, and underscores.
.TP
Password
Sends a password with the request.
.TP
Amount
Sends an amount with the request.  This option must be a base-10 number.
.TP
Time
Sends a time with the request.  This option must be a base-10 number but is
always optional.
.TP
Auth
Selects the username and password.  
.I n
is a one-based index into the configured
.I auth
array.  Alternatively, profide the full username and password of the user to
authenticate as.  The provided username must comply with
.B CCash
username restrictions (see
.IR name ),
and it must be combined with the password in HTTP basic authentification
fashion:
.IR username : password .
.TP
Server
Selects the server, 
.I n
is a one-based index into the configured
.I servers
array.  Alternatively, provide the full address of the server.  This is a
required argument.
.SH CUSTOMISATION
.BR ccash_cmd (1)
is customised by creating a custom
.I config.h
and (re)compiling the source code.  Additionally, command configuration is in
.I endpoint.h
and flag configuration is in
.IR arg.c ". "
Source code modification to configure
.BR ccash_cmd (1)
keeps it fast, secure, and
simple.
.SH EXAMPLE
To send a /admin/verify_account request using a configured auth:
.PP
.EX
ccash_cmd admin_verify_user --server ccash.example.com --auth @3
.EE
.PP
To send a /user/balance?... request:
.EX
ccash_cmd get_bal --server @1 --name user1
.EE
.PP
To send a /user/transfer request:
.PP
.EX
ccash_cmd send_funds -s @4 -n user3 -c 100 -a user2:passwd
.EE
.SH AUTHOR
Written by FearlessDoggo21.
