.TH CCASH_CMD 1 ccash_cmd\-VERSION
.SH NAME
ccash_cmd \- command line interface for ccash servers
.SH SYNOPSIS
.SY ccash_cmd
.OP "-n|--name" name
.OP "-p|--passwd" password
.OP "-c|--amount" amount
.OP "-t|--time" time
.OP "-a|--auth" auth
.OP "-s|--server" server
.YS
.SH DESCRIPTION
\fBccash_cmd\fP(1) is a command line utility for interfacing with \fBCCash\fP
servers.  It focuses on efficiency and is thus written with configuration in
mind.  Furthermore, simple flags and output formatting increase command
throughput.
.SH OPTIONS
.TP
[\fB\-n\fP|\fB\-\-name\fP = \fIname\fP]
Sends a name with the request.  The provided name must conform with \fBccash\fP
username restrictions: be between 3 and 16 characters long and be composed of
lowercase letters, numbers, and underscores.
.TP
[\fB\-p\fP|\fB\-\-passwd\fP] [\fIpasswd\fP]
Sends a password with the request.
.TP
[\fB\-c\fP|\fB\-\-amount\fP] [\fIamount\fP]
Sends an amount with the request.  This option must be a base-10 number.
.TP
[\fB\-t\fP|\fB\-\-time\fP] [\fItime\fP]
Sends a time with the request.  This option must be a base-10 number but is
always optional.
.TP
[\fB\-a\fP|\fB\-\-auth\fP] [\fB@\fIn\fP|\fIauth\fP]
Selects the username and password. \fIn\fP is a one-based index into the
configured \fIauth\fP array.  Alternatively, profide the full username and
password of the user to authenticate as.  The provided username must comply
with \fBccash\fP username restrictions (see \fIname\fP), and it must be
combined with the password in HTTP basic authentification fashion:
\fIusername\fP:\fIpassword\fP.
.TP
[\fB\-s\fP|\fB\-\-server\fP] [\fB@\fIn\fP|\fIserver\fP]
Selects the server, \fIn\fP is a one-based index into the configured
\fIservers\fP array.  Alternatively, provide the full address of the
server.  This is a required argument.
.SH CUSTOMISATION
\fBccash_cmd\fP(1) is customised by creating a custom \fIconfig.h\fP and
(re)compiling the source code.  Additionally, command configuration is in
\fIendpoint.h\fP and flag configuration is in \fIarg.c\fP.  Source code
modification to configure a program keeps it fast, secure, and simple.
.SH EXAMPLE
To send a /admin/verify_account request using a configured auth:
.PP
.EX
ccash_cmd admin_verify_user --server ccash.example.com --auth @3
.EE
.PP
To send a /user/balance?... request:
.EX
ccash_cmd get_bal --server @1 --name user1
.EE
.PP
To send a /user/transfer request:
.PP
.EX
ccash_cmd send_funds -s @4 -n user3 -c 100 -a user2:passwd
.EE
.SH AUTHOR
Written by FearlessDoggo21.
